[profile.default]
solc_version = "0.8.23"
solc = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]


[profile.deploy]
optimizer = true
optimizer_runs = 999999

[fmt]
sort_imports = true
wrap_comments = true